services:
  # Node.js Worker Service - Job orchestration, scraping, YouTube upload
  workers:
    build:
      context: ./workers
      dockerfile: Dockerfile
    container_name: pipeline-workers
    env_file:
      - ./workers/.env
    ports:
      - "3000:3000"
    volumes:
      - shared_storage:/app/shared
      - ./workers/logs:/app/logs
    depends_on:
      - face-processor
    restart: unless-stopped
    environment:
      - FACE_PROCESSOR_URL=http://face-processor:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Python Face Processing Service - Deface library processing
  face-processor:
    build:
      context: ./deface-with-selective-face-blurring
      dockerfile: Dockerfile
    container_name: pipeline-face-processor
    ports:
      - "5000:5000"
    volumes:
      - shared_storage:/app/shared
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  shared_storage:
    driver: local 