#!/bin/bash
# Run this script on your GCP VM to fix the face processor _version.py issue

echo "🔧 Fixing face processor _version.py issue on VM..."

# Navigate to deployment directory  
cd ~/pipeline-deployment

# Create the missing _version.py file in the face processor container
echo "📝 Creating missing deface/_version.py file..."
docker-compose -f docker-compose.production.yml exec face-processor sh -c 'cat > /app/deface/_version.py << "VERSIONEOF"
# file generated by setuptools_scm
# don'\''t change, don'\''t track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union
    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "1.5.0"
__version_tuple__ = version_tuple = (1, 5, 0)
VERSIONEOF'

# Restart the face processor container
echo "🔄 Restarting face processor container..."
docker-compose -f docker-compose.production.yml restart face-processor

# Wait for restart
sleep 15

# Show new logs
echo "📋 Face processor logs after fix:"
docker-compose -f docker-compose.production.yml logs --tail=20 face-processor

# Test the health endpoint
echo "🔍 Testing face processor health endpoint..."
sleep 5
curl -s http://localhost:5000/health | python3 -m json.tool || echo "Health endpoint not ready yet"

echo "✅ Fix applied successfully!" 